matrimony/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('matrimony_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matrimony_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
    ]
    
    RELIGION_CHOICES = [
        ('hindu', 'Hindu'),
        ('muslim', 'Muslim'),
        ('christian', 'Christian'),
        ('sikh', 'Sikh'),  
        ('unspecified', 'unspecified'),

    ]
    
    CASTE_CHOICES = [
    ('brahmin', 'Brahmin'),
    ('kshatriya', 'Kshatriya'),
    ('vaishya', 'Vaishya'),
    ('shudra', 'Shudra'),
    ('darzi', 'Darzi'),
    ('jolaha', 'Jolaha'),
    ('fakir', 'Fakir'),
    ('rangrez', 'Rangrez'),
    ('unspecified', 'unspecified'),

    # Add more caste choices as needed
]
    DISTRICT_CHOICES = [
    ('Thiruvananthapuram', 'Thiruvananthapuram'),
    ('Kollam', 'Kollam'),
    ('Pathanamthitta', 'Pathanamthitta'),
    ('Alappuzha', 'Alappuzha'),
    ('Kottayam', 'Kottayam'),
    ('Idukki', 'Idukki'),
    ('Ernakulam', 'Ernakulam'),
    ('Thrissur', 'Thrissur'),
    ('Palakkad', 'Palakkad'),
    ('Malappuram', 'Malappuram'),
    ('Kozhikode', 'Kozhikode (Calicut)'),
    ('Wayanad', 'Wayanad'),
    ('Kannur', 'Kannur'),
    ('Kasaragod', 'Kasaragod'),
]
    
    PLACE_CHOICES = [
    ('Thiruvananthapuram', [
        ('Thiruvananthapuram', 'Thiruvananthapuram'),
        ('Kovalam', 'Kovalam'),
        ('Neyyattinkara', 'Neyyattinkara'),
        ('Attingal', 'Attingal'),
        ('Varkala', 'Varkala'),
    ]),
    ('Kollam', [
        ('Kollam', 'Kollam'),
        ('Paravur', 'Paravur'),
        ('Punalur', 'Punalur'),
        ('Karunagappally', 'Karunagappally'),
    ]),
    ('Pathanamthitta', [
        ('Pathanamthitta', 'Pathanamthitta'),
        ('Adoor', 'Adoor'),
        ('Thiruvalla', 'Thiruvalla'),
        ('Ranni', 'Ranni'),
    ]),
    ('Alappuzha', [
        ('Alappuzha', 'Alappuzha'),
        ('Chengannur', 'Chengannur'),
        ('Kayamkulam', 'Kayamkulam'),
        ('Haripad', 'Haripad'),
        ('Ambalappuzha', 'Ambalappuzha'),
    ]),
    ('Kottayam', [
        ('Kottayam', 'Kottayam'),
        ('Changanassery', 'Changanassery'),
        ('Palai', 'Palai'),
        ('Vaikom', 'Vaikom'),
    ]),
    ('Idukki', [
        ('Idukki', 'Idukki'),
        ('Thodupuzha', 'Thodupuzha'),
        ('Munnar', 'Munnar'),
        ('Adimali', 'Adimali'),
    ]),
    ('Ernakulam', [
        ('Ernakulam', 'Ernakulam'),
        ('Kochi', 'Kochi'),
        ('Aluva', 'Aluva'),
        ('Paravur', 'Paravur'),
    ]),
    ('Thrissur', [
        ('Thrissur', 'Thrissur'),
        ('Chalakudy', 'Chalakudy'),
        ('Kodungallur', 'Kodungallur'),
        ('Irinjalakuda', 'Irinjalakuda'),
    ]),
    ('Palakkad', [
        ('Palakkad', 'Palakkad'),
        ('Ottapalam', 'Ottapalam'),
        ('Chittur', 'Chittur'),
        ('Mannarkkad', 'Mannarkkad'),
    ]),
    ('Malappuram', [
        ('Malappuram', 'Malappuram'),
        ('Manjeri', 'Manjeri'),
        ('Tirur', 'Tirur'),
        ('Perinthalmanna', 'Perinthalmanna'),
    ]),
    ('Kozhikode', [
        ('Calicut', 'Kozhikode (Calicut)'),
        ('Vadakara', 'Vadakara'),
        ('Thamarassery', 'Thamarassery'),
        ('Ramanattukara', 'Ramanattukara'),
    ]),
    ('Wayanad', [
        ('Wayanad', 'Wayanad'),
        ('Kalpetta', 'Kalpetta'),
        ('Sulthan Bathery', 'Sulthan Bathery'),
        ('Mananthavady', 'Mananthavady'),
    ]),
    ('Kannur', [
        ('Thalassery', 'Thalassery'),
        ('Kannur', 'Kannur'),
        ('Payyannur', 'Payyannur'),
        ('Thaliparamba', 'Thaliparamba'),
        ('Iritty', 'Iritty'),
    ]),
    ('Kasaragod', [
        ('Kasaragod', 'Kasaragod'),
        ('Kanhangad', 'Kanhangad'),
        ('Kumbala', 'Kumbala'),
        ('Cherkala', 'Cherkala'),
    ]),
]

    EDUCATION_CHOICES = [
    ('high_school', 'High School'),
    ('associate_degree', 'Associate Degree'),
    ('bachelors_degree', "Bachelor's Degree"),
    ('masters_degree', "Master's Degree"),
    ('doctorate', 'Doctorate'),
    ('others', 'others'),

]

    MARITAL_STATUS_CHOICES = [
    ('single', 'Single'),
    ('married', 'Married'),
    ('divorced', 'Divorced'),
    ('widowed', 'Widowed'),
]

    SIBLING_CHOICES = [
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        ('13', '13'),
        ('14', '14'),
        ('15', '15'),
        ('16', '16'),
        ('17', '17'),
        ('18', '18'),
        ('19', '19'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    custom_user_id = models.CharField(max_length=10, unique=True, blank=True, null=True)  # Corrected field name    date_of_birth = models.DateField()
    address = models.TextField()
    education = models.CharField(max_length=20, choices=EDUCATION_CHOICES)
    selected_course = models.CharField(max_length=20, blank=True, null=True) 
    job = models.CharField(max_length=100)
    worked_at= models.CharField(max_length=100,null=True,blank=True)

    religion = models.CharField(max_length=20, choices=RELIGION_CHOICES)
    caste = models.CharField(max_length=20, choices=CASTE_CHOICES)
    district = models.CharField(max_length=50, choices=DISTRICT_CHOICES)
    place = models.CharField(max_length=100, choices=PLACE_CHOICES)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    photo_1 = models.ImageField(upload_to='user_photos/', blank=True, null=True)
    photo_2 = models.ImageField(upload_to='user_photos/', blank=True, null=True)
    photo_3 = models.ImageField(upload_to='user_photos/', blank=True, null=True)
    photo_4 = models.ImageField(upload_to='user_photos/', blank=True, null=True)
    height = models.CharField(max_length=10)
    age = models.IntegerField()
    mob = models.CharField(max_length=20)
    date_of_birth = models.DateField(null=True)
    marital_status = models.CharField(max_length=20, choices=MARITAL_STATUS_CHOICES,null=True,blank=True)
    mother_name = models.CharField(max_length=100, blank=True, null=True)
    father_name = models.CharField(max_length=100, blank=True, null=True)
    father_job = models.CharField(max_length=100, blank=True, null=True)
    mother_job = models.CharField(max_length=100, blank=True, null=True)  # Field for mother's job
   
    about = models.TextField(blank=True, null=True)
    is_approved = models.BooleanField(default=False)
    male_siblings = models.IntegerField(blank=True, null=True)
    female_siblings = models.IntegerField(blank=True, null=True)
    married_male_siblings = models.IntegerField(blank=True, null=True)
    married_female_siblings = models.IntegerField(blank=True, null=True) 
    def __str__(self):
        return self.user.username





class Interest(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    interest_user = models.ForeignKey(UserProfile, related_name='interests', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.user.username} -> {self.interest_user.user.username}'

class Match(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    match_user = models.ForeignKey(UserProfile, related_name='matches', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.user.username} matched with {self.match_user.user.username}'



class SubscriptionPlan(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    payment_date = models.DateTimeField(auto_now_add=True, null=True)
    expiration_date = models.DateTimeField(null=True)  # Add this field for expiration date
    def __str__(self):
        return self.name



from django.utils.translation import gettext_lazy as _

class Report(models.Model):
    REASON_CHOICES = [
        ('spam', 'Spam'),
        ('inappropriate_content', 'Inappropriate Content'),
        ('harassment', 'Harassment'),
        ('fake_profile', 'Fake Profile'),
        
    ]
    
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    reported_user = models.ForeignKey(UserProfile, related_name='reported_users', on_delete=models.CASCADE)
    reason = models.CharField(max_length=50, choices=REASON_CHOICES)
    description = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = _("Report")
        verbose_name_plural = _("Reports")
    
    def __str__(self):
        return f'{self.user.user.username} reported {self.reported_user.user.username}'



class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"From {self.sender.username} to {self.receiver.username} ({self.timestamp.strftime('%Y-%m-%d %H:%M:%S')})"

templates/copy/copy.html
<div class="main">
    <h1>User Profiles</h1>

    <table class="table table-striped" id="user-profiles-table">
                    <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Religion</th>
                <th>Caste</th>
                <th>District</th>
                <th>Place</th>
                <th>Education</th>
                <th>Job</th>
                <th>Height</th>
                <th>Age</th>
                <th>Mobile Number</th>
                <!-- Add more headers for additional fields -->
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for profile in user_profiles %}
            <tr>
                <td>{{ profile.user.id }}</td>
                <td>{{ profile.user.username }}</td>
                <td>{{ profile.user.email }}</td>
                <td>{{ profile.get_gender_display }}</td>
                <td>{{ profile.get_religion_display }}</td>
                <td>{{ profile.get_caste_display }}</td>
                <td>{{ profile.district }}</td>
                <td>{{ profile.place }}</td>
                <td>{{ profile.get_education_display }}</td>
                <td>{{ profile.job }}</td>
                <td>{{ profile.height }}</td>
                <td>{{ profile.age }}</td>
                <td>{{ profile.mob }}</td>
                <!-- Add more <td> elements for additional fields -->
                <td>
                    <!-- Add action buttons or links here -->
                </td>
                <td>
                    <form method="post" action="{% url 'approve_profile' profile.user.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Approve</button>
                    </form>
                    
                    <form method="post" action="{% url 'reject_profile' profile.user.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Reject</button>
                    </form>
                                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>



    <p><strong>Name:</strong> {{ profile.user.username }}</p>
    <p><strong>Education:</strong> {{ profile.education }}</p>
    <p><strong>Religion:</strong> {{ profile.religion }}</p>
    <p><strong>Age:</strong> {{ profile.age }}</p>
    <p><strong>Job:</strong> {{ profile.job }}</p>
    <p><strong>Place:</strong> {{ profile.place }}</p>








    <div id="white">
        <br>
        <br>
        <h2 class="text-center" style="color:#D93B38;">Recent Updates</h2>
    
        <br>
        <br>
    
        <section id="section">
          <ul>
            <li class="image_wrapper">
              <img src="https://th.bing.com/th/id/R.1939678e62beb7f10bc14b9da5d23389?rik=%2f9ugCpsHALZVeQ&riu=http%3a%2f%2florrye.net%2fimages5%2f0817L%2fbest-gents-hair-styles%2fbest-gents-hair-styles-90_6.jpg&ehk=GQtZ1Xeg8p4tFYtGkJgwVR0IEvLdC6%2fNqxQbt9mL1CI%3d&risl=&pid=ImgRaw&r=0" alt="" style="width: 300px; height: 480px;" />
              <div class="overlay overlay_4">
                <h3>You Need To login</h3>
              </div>
            </li>
            <li class="image_wrapper">
              <img src="https://i.pinimg.com/736x/5d/54/06/5d54066cbfb3f13cb718885c4b6abc48.jpg" alt="" style="width: 300px; height: 480px;" />
              <div class="overlay overlay_4">
                <h3>You Need To login</h3>
              </div>
            </li>
            <li class="image_wrapper">
              <img src="https://th.bing.com/th/id/OIP.LfBtLCx5jWjmzpI_LDs5TwHaL-?pid=ImgDet&rs=1" alt="" style="width: 300px; height: auto;" />
              <div class="overlay overlay_4">
                <h3>You Need To login</h3>
              </div>
            </li>
            <li class="image_wrapper">
              <img src="https://th.bing.com/th/id/R.8a47231b47cb896a41b50250ffd31a07?rik=xMqtW2%2fgrcYPFQ&riu=http%3a%2f%2f4.bp.blogspot.com%2f-hBuAm7n4E94%2fTimwc7G-kjI%2fAAAAAAAAAAM%2fM1lZKi574lQ%2fs400%2fCindy%2bCrawford%2bHairstyle%2b1.jpg&ehk=pbaG1kLsIbqt%2fEcAYFMLq3biBzAVv53zWA4QdGEJeoo%3d&risl=&pid=ImgRaw&r=0" alt="" style="width: 300px; height: 480px;" />
              <div class="overlay overlay_4">
                <h3>You Need To login</h3>
              </div>
            </li>
          </ul>
        </section>
        <br>
        <br>
        <br>
        <br>
      </div>









      <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" style="font-size: 40px;">User Profile</div>
                    <marquee behavior="scroll" direction="left" class="mt-3">
                        {% if subscriptions %}
                            {% with has_active_plans=False %}
                                {% for subscription in subscriptions %}
                                    {% if subscription.expiration_date >= now %}
                                        Plan: {{ subscription.name }} Rs - Expiry Date: {{ subscription.expiration_date|date:"F j, Y" }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        {% with has_active_plans=True %}
                                        {% endwith %}
                                    {% endif %}
                                {% endfor %}
                                {% if not has_active_plans %}
                                    <h4> No active plans</h4>
                                {% endif %}
                            {% endwith %}
                        {% else %}
                            <h4> No plans yet</h4>
                        {% endif %}
                    </marquee>
                    
                    
                    <div class="card-body">
                        <div class="text-center">
                            <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
                            <h2>{{ user_profile.user.username }}</h2>
                        </div>
                        <hr>
                        <p><strong>Education: {{ user_profile.education }}</strong></p>
                        <p><strong>Selected Course: {{ user_profile.selected_course }}</strong></p>
                        <p><strong>Job:{{ user_profile.job }}</strong></p>
                        <p><strong>Religion:{{ user_profile.religion }}</strong></p>
                        <p><strong>Caste:{{ user_profile.caste }}</strong></p>
                        <p><strong>District:{{ user_profile.district }}</strong></p>
                        <p><strong>Place:{{ user_profile.place }}</strong></p>
                        <p><strong>Gender:{{ user_profile.get_gender_display }}</strong></p>
                        <p><strong>Custom User ID:{{ user_profile.custom_user_id }}</strong></p>
                        <p><strong>Worked At:{{ user_profile.worked_at }}</strong></p>
                        <p><strong>Height:{{ user_profile.height }}</strong></p>
                        <p><strong>Age:{{ user_profile.age }}</strong></p>
                        <p><strong>Mobile:{{ user_profile.mob }}</p>
                            <p><strong>Email:{{ user_profile.user.email }}</p>
    
                        <p><strong>Date of Birth:{{ user_profile.date_of_birth }}</strong></p>
                        <p><strong>Marital Status:{{ user_profile.marital_status }}</strong></p>
                        <p><strong>Mother's Name:{{ user_profile.mother_name }}</strong></p>
                        <p><strong>Father's Name:{{ user_profile.father_name }}</strong></p>
                        <p><strong>Father_job:{{ user_profile.father_job }}</strong></p>
                        <p><strong>Mother_job:{{ user_profile.mother_job }}</strong></p>
    <!-- Sibling Information -->
    <p><strong>Male Siblings:{{ user_profile.male_siblings }}</strong></p>
    <p><strong>Female Siblings:{{ user_profile.female_siblings }}</strong></p>
    <p><strong>Married Male Siblings:{{ user_profile.married_male_siblings }}</strong></p>
    <p><strong>Married Female Siblings:{{ user_profile.married_female_siblings }}</strong></p>
    
                        <p><strong>About:{{ user_profile.about }}</strong></p>    
                                        <div class="text-center mt-3">
                            <a href="{% url 'edit_photos' %}" class="btn btn-" style="background-color:white;color:#D93B38;font-weight:bold;">Edit Photos</a>
    
                            <a href="{% url 'edit_profile' %}" class="btn btn-" style="background-color:white;color:#D93B38;font-weight:bold;">
                                Edit Profile
                            </a>
                            <a href="{% url 'change_password' %}" class="btn btn-" style="background-color:white;color:#D93B38;font-weight:bold;">
                                Change Password
                            </a> <button onclick="printUserProfile()" class="btn btn-" style="background-color:white;color:#D93B38;font-weight:bold;">
                                Print Profile
                            </button>
                                    </div>
                  
                </div>
               
            </div>
      
        </div>
    </div>
    </div>
    